version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: san_giorno
      MYSQL_USER: san_giorno
      MYSQL_PASSWORD: san_giorno
      MYSQL_ROOT_PASSWORD: san_giorno
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      - san-giorno-network

  rabbitmq:
    image: rabbitmq:management
    environment:
      RABBITMQ_DEFAULT_USER: san-giorno
      RABBITMQ_DEFAULT_PASS: san-giorno
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - san-giorno-network

networks:
  san-giorno-network:
    driver: bridge

volumes:
  mysqldata:
