version: '3.8'
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: san-giorno
      MYSQL_DATABASE: san_giorno
      MYSQL_USER: san-giorno
      MYSQL_PASSWORD: san-giorno
    ports:
      - "3306:3306"
    networks:
      - san-giorno-network
    volumes:
      - mysqldata:/var/lib/mysql
  app:
    image: san-giorno-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/san_giorno
      SPRING_DATASOURCE_USERNAME: san-giorno
      SPRING_DATASOURCE_PASSWORD: san-giorno
    depends_on:
      - mysql
    networks:
      - san-giorno-network

  rabbitmq:
    image: rabbitmq:management
    environment:
      RABBITMQ_DEFAULT_USER: san-giorno
      RABBITMQ_DEFAULT_PASS: san-giorno
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - san-giorno-network

networks:
  san-giorno-network:
    driver: bridge

volumes:
  mysqldata:
